image: cypress/base:latest

pipelines:
  custom:
    schedule_cypress_run:
      - step:
          name: "Run Cypress Automation with Report"
          caches:
            - node
          script:
            - npm ci  # Install dependencies
            - npm run cy:run_report  # Run the Cypress test and generate the report

pipelines:
  schedules:
    - cron: "0 16 * * *"  # This will trigger the pipeline at 7 PM +3 GMT (4 PM UTC)
      pipeline: 
        custom: 
          - schedule_cypress_run
