name: Cypress Tests

# Schedule workflow to run at 7:30 PM Cairo time (UTC+2) every day
on:
  schedule:
    - cron: "11 01 * * 2"  # Runs every Tuesday at 11:01 UTC, which is 11:01 AM Cairo (UTC+2)
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI  

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.12.2']  # Specify the Node.js version you'd like to test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Clean npm cache before installing dependencies
    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install

    # Delete all JSON, CSV, and HTML files under cypress/reports folder before running tests
    - name: Clean reports folder
      run: rm -rf cypress/reports/*.json cypress/reports/*.csv cypress/reports/*.html

    - name: Run Cypress Tests
      run: npm run cy:run

    - name: Generate Cypress Reports
      run: npm run all:reports

    # Archive all test results (reports) for future use
    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-reports
        path: cypress/reports

    # Display the Cypress merged HTML report on the GitHub Actions page
    - name: Display HTML Report
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}  # Replace with your token secret
        publish_dir: cypress/reports/
        publish_branch: gh-pages
        user_name: 'GitHub Actions'
        user_email: 'actions@github.com'

    # Compress all report files for email attachment
    - name: Compress Reports Folder
      if: always()
      run: zip -r reports.zip cypress/reports

    # Send email with the reports folder as an attachment
    - name: Send Cypress Report Email
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Daily Cypress Report"
        to: mohamedscitech@outlook.com
        from: bensyed096@gmail.com
        body: "Cypress tests have been executed. You can find the attached reports below."
        attachments: reports.zip  # Compressed reports folder